config/routes.rb
Rails.application.routes.draw do
  devise_for :talents
  devise_for :clients
  root to: "home#index"

  resources :talents
  resources :bookings
  resources :jobs
  resources :clients
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/talent.rb
class Talent < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :booking, optional: true
end

app/controllers/talents_controller.rb
class TalentsController < ApplicationController
  before_action :authenticate_talent!
  before_action :set_talent, only: [:show, :edit, :update, :destroy]

  # GET /talents
  # GET /talents.json
  def index
    @talents = Talent.all
  end

  # GET /talents/1
  # GET /talents/1.json
  def show
  end

  # GET /talents/new
  def new
    @talent = Talent.new
  end

  # GET /talents/1/edit
  def edit
  end

  # POST /talents
  # POST /talents.json
  def create
    @talent = Talent.new(talent_params)

    respond_to do |format|
      if @talent.save
        format.html { redirect_to @talent, notice: 'Talent was successfully created.' }
        format.json { render :show, status: :created, location: @talent }
      else
        format.html { render :new }
        format.json { render json: @talent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /talents/1
  # PATCH/PUT /talents/1.json
  def update
    respond_to do |format|
      if @talent.update(talent_params)
        format.html { redirect_to @talent, notice: 'Talent was successfully updated.' }
        format.json { render :show, status: :ok, location: @talent }
      else
        format.html { render :edit }
        format.json { render json: @talent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /talents/1
  # DELETE /talents/1.json
  def destroy
    @talent.destroy
    respond_to do |format|
      format.html { redirect_to talents_url, notice: 'Talent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_talent
      @talent = Talent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def talent_params
      params.require(:talent).permit(:username, :first_name, :middle_name, :last_name, :biography, :phone, :address, :address2, :city, :state, :zipcode, :sex, :birthday, :government_id, :topsuit, :waisthip, :pantlength, :eyecolor, :has_visible_tattoo, :booking_id)
    end
end

app/helpers/talents_helper.rb
module TalentsHelper
end

app/views/talents/_form.html.erb
<%= form_with(model: talent, local: true) do |form| %>
  <% if talent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(talent.errors.count, "error") %> prohibited this talent from being saved:</h2>

      <ul>
      <% talent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username, id: :talent_username %>
  </div>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :talent_first_name %>
  </div>

  <div class="field">
    <%= form.label :middle_name %>
    <%= form.text_field :middle_name, id: :talent_middle_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :talent_last_name %>
  </div>

  <div class="field">
    <%= form.label :biography %>
    <%= form.text_area :biography, id: :talent_biography %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :talent_phone %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :talent_address %>
  </div>

  <div class="field">
    <%= form.label :address2 %>
    <%= form.text_field :address2, id: :talent_address2 %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :talent_city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state, id: :talent_state %>
  </div>

  <div class="field">
    <%= form.label :zipcode %>
    <%= form.text_field :zipcode, id: :talent_zipcode %>
  </div>

  <div class="field">
    <%= form.label :sex %>
    <%= form.text_field :sex, id: :talent_sex %>
  </div>

  <div class="field">
    <%= form.label :birthday %>
    <%= form.date_select :birthday, id: :talent_birthday %>
  </div>

  <div class="field">
    <%= form.label :government_id %>
    <%= form.text_field :government_id, id: :talent_government_id %>
  </div>

  <div class="field">
    <%= form.label :topsuit %>
    <%= form.text_field :topsuit, id: :talent_topsuit %>
  </div>

  <div class="field">
    <%= form.label :waisthip %>
    <%= form.text_field :waisthip, id: :talent_waisthip %>
  </div>

  <div class="field">
    <%= form.label :pantlength %>
    <%= form.text_field :pantlength, id: :talent_pantlength %>
  </div>

  <div class="field">
    <%= form.label :eyecolor %>
    <%= form.text_field :eyecolor, id: :talent_eyecolor %>
  </div>

  <div class="field">
    <%= form.label :has_visible_tattoo %>
    <%= form.check_box :has_visible_tattoo, id: :talent_has_visible_tattoo %>
  </div>

  <div class="field">
    <%= form.label :booking_id %>
    <%= form.text_field :booking_id, id: :talent_booking_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/talents/edit.html.erb
<h1>Editing Talent</h1>

<%= render 'form', talent: @talent %>

<%= link_to 'Show', @talent %> |
<%= link_to 'Back', talents_path %>

app/views/talents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Talents</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>First name</th>
      <th>Middle name</th>
      <th>Last name</th>
      <th>Biography</th>
      <th>Phone</th>
      <th>Address</th>
      <th>Address2</th>
      <th>City</th>
      <th>State</th>
      <th>Zipcode</th>
      <th>Sex</th>
      <th>Birthday</th>
      <th>Government</th>
      <th>Topsuit</th>
      <th>Waisthip</th>
      <th>Pantlength</th>
      <th>Eyecolor</th>
      <th>Has visible tattoo</th>
      <th>Booking</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @talents.each do |talent| %>
      <tr>
        <td><%= talent.username %></td>
        <td><%= talent.first_name %></td>
        <td><%= talent.middle_name %></td>
        <td><%= talent.last_name %></td>
        <td><%= talent.biography %></td>
        <td><%= talent.phone %></td>
        <td><%= talent.address %></td>
        <td><%= talent.address2 %></td>
        <td><%= talent.city %></td>
        <td><%= talent.state %></td>
        <td><%= talent.zipcode %></td>
        <td><%= talent.sex %></td>
        <td><%= talent.birthday %></td>
        <td><%= talent.government_id %></td>
        <td><%= talent.topsuit %></td>
        <td><%= talent.waisthip %></td>
        <td><%= talent.pantlength %></td>
        <td><%= talent.eyecolor %></td>
        <td><%= talent.has_visible_tattoo %></td>
        <td><%= talent.booking %></td>
        <td><%= link_to 'Show', talent %></td>
        <td><%= link_to 'Edit', edit_talent_path(talent) %></td>
        <td><%= link_to 'Destroy', talent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Talent', new_talent_path %>

app/views/talents/new.html.erb
<h1>New Talent</h1>

<%= render 'form', talent: @talent %>

<%= link_to 'Back', talents_path %>

app/views/talents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @talent.username %>
</p>

<p>
  <strong>First name:</strong>
  <%= @talent.first_name %>
</p>

<p>
  <strong>Middle name:</strong>
  <%= @talent.middle_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @talent.last_name %>
</p>

<p>
  <strong>Biography:</strong>
  <%= @talent.biography %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @talent.phone %>
</p>

<p>
  <strong>Address:</strong>
  <%= @talent.address %>
</p>

<p>
  <strong>Address2:</strong>
  <%= @talent.address2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @talent.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @talent.state %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @talent.zipcode %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @talent.sex %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @talent.birthday %>
</p>

<p>
  <strong>Government:</strong>
  <%= @talent.government_id %>
</p>

<p>
  <strong>Topsuit:</strong>
  <%= @talent.topsuit %>
</p>

<p>
  <strong>Waisthip:</strong>
  <%= @talent.waisthip %>
</p>

<p>
  <strong>Pantlength:</strong>
  <%= @talent.pantlength %>
</p>

<p>
  <strong>Eyecolor:</strong>
  <%= @talent.eyecolor %>
</p>

<p>
  <strong>Has visible tattoo:</strong>
  <%= @talent.has_visible_tattoo %>
</p>

<p>
  <strong>Booking:</strong>
  <%= @talent.booking %>
</p>

<%= link_to 'Edit', edit_talent_path(@talent) %> |
<%= link_to 'Back', talents_path %>